// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdPGKuJgfquy0dYthh4l3Yxldpz_Yyr0I',
    appId: '1:481241273005:web:448609d56cdfd86ccd2c24',
    messagingSenderId: '481241273005',
    projectId: 'insureme-login',
    authDomain: 'insureme-login.firebaseapp.com',
    storageBucket: 'insureme-login.appspot.com',
    measurementId: 'G-6XB6E77B1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqyP0fbCB2uyyhHVzw6VjGayApo48PYZY',
    appId: '1:481241273005:android:891a6f0b821a5ccacd2c24',
    messagingSenderId: '481241273005',
    projectId: 'insureme-login',
    storageBucket: 'insureme-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRCmD-pO6CqDbO7dywRzHTVeDn7Su9gFg',
    appId: '1:481241273005:ios:002b53fe66aafb18cd2c24',
    messagingSenderId: '481241273005',
    projectId: 'insureme-login',
    storageBucket: 'insureme-login.appspot.com',
    androidClientId: '481241273005-31i8qd2inocf0liv6vdt5i9k4v43g02j.apps.googleusercontent.com',
    iosClientId: '481241273005-r299jb6stivjs2qsoqcbejcdba96248s.apps.googleusercontent.com',
    iosBundleId: 'com.example.insureme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRCmD-pO6CqDbO7dywRzHTVeDn7Su9gFg',
    appId: '1:481241273005:ios:002b53fe66aafb18cd2c24',
    messagingSenderId: '481241273005',
    projectId: 'insureme-login',
    storageBucket: 'insureme-login.appspot.com',
    androidClientId: '481241273005-31i8qd2inocf0liv6vdt5i9k4v43g02j.apps.googleusercontent.com',
    iosClientId: '481241273005-r299jb6stivjs2qsoqcbejcdba96248s.apps.googleusercontent.com',
    iosBundleId: 'com.example.insureme',
  );
}
